# Site settings
title: Kiripesa
email: hello@kiripesa.eu
description: > # this means to ignore newlines until "baseurl:"
  Press &amp; Artist Production
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kiripesa.eu" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

gaid: UA-69289925-1